objs: ticket_server ticket_client

ticket_server:ticket_server.c
	gcc ticket_server.c -o ticket_server -lpthread
ticket_client:ticket_client.c
	gcc ticket_client.c -o ticket_client 
clean:
	rm ticket_server ticket_client
